# Generated by Django 4.2.2 on 2023-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_discover_discover2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discover2',
            name='cover2',
            field=models.CharField(max_length=500),
        ),
    ]
